#!/usr/bin/env bash
# setup.sh — HexPlayer one-click installer
# ─────────────────────────────────────────
# Run as the pi / your normal user (NOT root directly).
# Requires sudo access for system-level operations.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="hexplayer"
SERVICE_FILE="$SCRIPT_DIR/systemd/${SERVICE_NAME}.service"
VENV_DIR="$SCRIPT_DIR/venv"
INSTALL_USER="${SUDO_USER:-${USER}}"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
info()  { echo -e "${CYAN}ℹ️  $*${RESET}"; }
ok()    { echo -e "${GREEN}✅  $*${RESET}"; }
warn()  { echo -e "${YELLOW}⚠️  $*${RESET}"; }
err()   { echo -e "${RED}❌  $*${RESET}" >&2; exit 1; }
step()  { echo; echo -e "${BOLD}${CYAN}── $* ──────────────────────────────────${RESET}"; }

echo
echo -e "${BOLD}╔══════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║  🎵  HexPlayer Setup Script          ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════╝${RESET}"
echo

# ── Sanity checks ─────────────────────────────────────────────────────────────
[[ "$(uname -m)" =~ ^arm|aarch64 ]] || warn "This script is designed for Raspberry Pi (ARM). Proceeding anyway."
command -v python3 >/dev/null 2>&1 || err "python3 not found. Install with: sudo apt install python3"
command -v pip3 >/dev/null 2>&1 || warn "pip3 not found — will install via apt"

# ── System packages ───────────────────────────────────────────────────────────
step "Updating package lists"
sudo apt-get update -y

step "Installing system dependencies"
sudo apt-get install -y \
    python3 python3-pip python3-venv python3-dev \
    libssl-dev libffi-dev \
    git curl wget \
    spi-tools \
    2>/dev/null || warn "Some packages may have failed — continuing"
ok "System dependencies installed"

# ── Enable SPI ────────────────────────────────────────────────────────────────
step "Enabling SPI interface"
if grep -q "^dtparam=spi=on" /boot/firmware/config.txt 2>/dev/null; then
    ok "SPI already enabled in /boot/firmware/config.txt"
elif grep -q "^dtparam=spi=on" /boot/config.txt 2>/dev/null; then
    ok "SPI already enabled in /boot/config.txt"
else
    CONFIG_FILE="/boot/firmware/config.txt"
    [[ -f "$CONFIG_FILE" ]] || CONFIG_FILE="/boot/config.txt"
    echo "dtparam=spi=on" | sudo tee -a "$CONFIG_FILE" > /dev/null
    ok "SPI enabled in $CONFIG_FILE — will take effect after reboot"
fi

# ── I2S / HiFiBerry overlay ───────────────────────────────────────────────────
step "Configuring I2S audio overlay"
CONFIG_FILE="/boot/firmware/config.txt"
[[ -f "$CONFIG_FILE" ]] || CONFIG_FILE="/boot/config.txt"

# Disable the default onboard audio to avoid conflicts
if ! grep -q "^dtparam=audio=off" "$CONFIG_FILE" 2>/dev/null; then
    # Comment out any existing audio=on line
    sudo sed -i 's/^dtparam=audio=on/#dtparam=audio=on  # disabled by hexplayer setup/' "$CONFIG_FILE"
    echo "dtparam=audio=off" | sudo tee -a "$CONFIG_FILE" > /dev/null
    ok "Disabled onboard audio"
fi

# Add HiFiBerry DAC+ / MAX98357 overlay if not already present
if ! grep -q "^dtoverlay=hifiberry-dac" "$CONFIG_FILE" 2>/dev/null; then
    echo "" | sudo tee -a "$CONFIG_FILE" > /dev/null
    echo "# HexPlayer — I2S DAC overlay (edit if using a different HAT)" | sudo tee -a "$CONFIG_FILE" > /dev/null
    echo "dtoverlay=hifiberry-dac" | sudo tee -a "$CONFIG_FILE" > /dev/null
    ok "I2S overlay (hifiberry-dac) added to $CONFIG_FILE"
else
    ok "I2S overlay already configured"
fi

# ── ALSA configuration ────────────────────────────────────────────────────────
step "Writing ALSA configuration"
ALSA_CONF="/etc/asound.conf"
if [[ ! -f "$ALSA_CONF" ]]; then
    sudo tee "$ALSA_CONF" > /dev/null <<'EOF'
# /etc/asound.conf — generated by HexPlayer setup.sh
pcm.!default {
    type hw
    card 0
}
ctl.!default {
    type hw
    card 0
}
EOF
    ok "ALSA configuration written to $ALSA_CONF"
else
    warn "$ALSA_CONF already exists — not overwriting"
fi

# ── Raspotify ─────────────────────────────────────────────────────────────────
step "Installing Raspotify (Spotify Connect)"
if command -v raspotify >/dev/null 2>&1 || systemctl list-units --full -all 2>/dev/null | grep -q "raspotify"; then
    ok "Raspotify already installed"
else
    info "Downloading and running Raspotify installer…"
    curl -sL https://dtcooper.github.io/raspotify/install.sh | sudo sh || {
        warn "Raspotify installer failed — you may need to install it manually."
        warn "See: https://github.com/dtcooper/raspotify"
    }
fi

# Customise the Raspotify device name.
# Read DEVICE_NAME from .env if it exists, otherwise fall back to 'HexPlayer'.
RASPOTIFY_CONF="/etc/raspotify/conf"
if [[ -f "$RASPOTIFY_CONF" ]] && grep -q "LIBRESPOT_NAME" "$RASPOTIFY_CONF"; then
    # Source .env to pick up DEVICE_NAME if the user has already edited it
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        DEVICE_NAME="$(grep -E '^DEVICE_NAME=' "$SCRIPT_DIR/.env" | cut -d= -f2- | tr -d '"' | tr -d "'")"
    fi
    DEVICE_NAME="${DEVICE_NAME:-HexPlayer}"
    sudo sed -i "s|^#*LIBRESPOT_NAME=.*|LIBRESPOT_NAME=\"${DEVICE_NAME}\"|" "$RASPOTIFY_CONF"
    ok "Raspotify device name set to '${DEVICE_NAME}'"
fi

sudo systemctl enable raspotify 2>/dev/null || true
sudo systemctl start  raspotify 2>/dev/null || true

# ── Python virtualenv ─────────────────────────────────────────────────────────
step "Creating Python virtual environment"
if [[ ! -d "$VENV_DIR" ]]; then
    python3 -m venv "$VENV_DIR"
    ok "Virtualenv created at $VENV_DIR"
else
    ok "Virtualenv already exists at $VENV_DIR"
fi

step "Installing Python dependencies"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install -r "$SCRIPT_DIR/requirements.txt" --quiet
ok "Python dependencies installed"

# ── .env file ─────────────────────────────────────────────────────────────────
step "Setting up .env credentials file"
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
    cp "$SCRIPT_DIR/.env.example" "$SCRIPT_DIR/.env"
    warn ".env created from .env.example"
    warn "Edit $SCRIPT_DIR/.env and add your Spotify credentials before starting the service."
else
    ok ".env already exists"
fi

# ── tiles.json ────────────────────────────────────────────────────────────────
step "Initialising tiles.json"
if [[ ! -f "$SCRIPT_DIR/tiles.json" ]]; then
    echo "{}" > "$SCRIPT_DIR/tiles.json"
    ok "Empty tiles.json created"
else
    ok "tiles.json already exists"
fi

# ── systemd service ───────────────────────────────────────────────────────────
step "Installing systemd service"
if [[ ! -f "$SERVICE_FILE" ]]; then
    err "Service file not found: $SERVICE_FILE"
fi

# Patch the service file paths to match the actual install location
TEMP_SERVICE=$(mktemp)
sed \
    -e "s|/opt/hexplayer|${SCRIPT_DIR}|g" \
    -e "s|User=pi|User=${INSTALL_USER}|g" \
    "$SERVICE_FILE" > "$TEMP_SERVICE"

sudo cp "$TEMP_SERVICE" "/etc/systemd/system/${SERVICE_NAME}.service"
rm -f "$TEMP_SERVICE"

sudo systemctl daemon-reload
sudo systemctl enable "${SERVICE_NAME}"
ok "systemd service '${SERVICE_NAME}' installed and enabled"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║  🎉  HexPlayer setup complete!                       ║${RESET}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════╝${RESET}"
echo
echo -e "${BOLD}Next steps:${RESET}"
echo "  1. Edit your credentials:  nano ${SCRIPT_DIR}/.env"
echo "  2. Run the Spotify auth:   ${VENV_DIR}/bin/python3 ${SCRIPT_DIR}/hexplayer.py"
echo "     (complete the browser auth, then Ctrl+C)"
echo "  3. Register tiles:         ${VENV_DIR}/bin/python3 ${SCRIPT_DIR}/register.py"
echo "  4. Start the service:      sudo systemctl start ${SERVICE_NAME}"
echo "  5. Check logs:             journalctl -u ${SERVICE_NAME} -f"
echo
echo -e "${YELLOW}⚠️  A reboot is recommended to activate SPI and the I2S overlay.${RESET}"
echo "    sudo reboot"
echo
